// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lark-hotel-server/internal/dao/internal"
)

// internalBillDao is internal type for wrapping internal DAO implements.
type internalBillDao = *internal.BillDao

// billDao is the data access object for table bill.
// You can define custom methods on it to extend its functionality as you wish.
type billDao struct {
	internalBillDao
}

var (
	// Bill is globally public accessible object for table bill operations.
	Bill = billDao{
		internal.NewBillDao(),
	}
)

// Fill with you ideas below.
