// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lark-hotel-server/internal/dao/internal"
)

// internalLarkEventOperationLogDao is internal type for wrapping internal DAO implements.
type internalLarkEventOperationLogDao = *internal.LarkEventOperationLogDao

// larkEventOperationLogDao is the data access object for table lark_event_operation_log.
// You can define custom methods on it to extend its functionality as you wish.
type larkEventOperationLogDao struct {
	internalLarkEventOperationLogDao
}

var (
	// LarkEventOperationLog is globally public accessible object for table lark_event_operation_log operations.
	LarkEventOperationLog = larkEventOperationLogDao{
		internal.NewLarkEventOperationLogDao(),
	}
)

// Fill with you ideas below.
