// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lark-hotel-server/internal/dao/internal"
)

// internalLarkAppInfoDao is internal type for wrapping internal DAO implements.
type internalLarkAppInfoDao = *internal.LarkAppInfoDao

// larkAppInfoDao is the data access object for table lark_app_info.
// You can define custom methods on it to extend its functionality as you wish.
type larkAppInfoDao struct {
	internalLarkAppInfoDao
}

var (
	// LarkAppInfo is globally public accessible object for table lark_app_info operations.
	LarkAppInfo = larkAppInfoDao{
		internal.NewLarkAppInfoDao(),
	}
)

// Fill with you ideas below.
