// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lark-hotel-server/internal/dao/internal"
)

// internalReportLogsDao is internal type for wrapping internal DAO implements.
type internalReportLogsDao = *internal.ReportLogsDao

// reportLogsDao is the data access object for table report_logs.
// You can define custom methods on it to extend its functionality as you wish.
type reportLogsDao struct {
	internalReportLogsDao
}

var (
	// ReportLogs is globally public accessible object for table report_logs operations.
	ReportLogs = reportLogsDao{
		internal.NewReportLogsDao(),
	}
)

// Fill with you ideas below.
