// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lark-hotel-server/internal/dao/internal"
)

// internalReportCustomerDao is internal type for wrapping internal DAO implements.
type internalReportCustomerDao = *internal.ReportCustomerDao

// reportCustomerDao is the data access object for table report_customer.
// You can define custom methods on it to extend its functionality as you wish.
type reportCustomerDao struct {
	internalReportCustomerDao
}

var (
	// ReportCustomer is globally public accessible object for table report_customer operations.
	ReportCustomer = reportCustomerDao{
		internal.NewReportCustomerDao(),
	}
)

// Fill with you ideas below.
